### ISSUE TITLE
Storing Eth Stats in Postgress

### ISSUE THREAD

**Issue by ferigis** [poanetwork/poa-netstats-warehouse#55]
Create a Receiver subscribed to ethereum stats which will store the metrics in a DB

**Comment by Chery46** [comment]
20:41:36.426 [warn] Error unexpected sending with POST, the reason is {:tls_alert, 'bad certificate'}
20:41:38.533 [info] ['TLS', 32, 'client', 58, 32, 73, 110, 32, 115, 116, 97, 116, 101, 32, 'certify', 32, 'at ssl_handshake.erl:1293 generated CLIENT ALERT: Fatal - Bad Certificate', 10]

Issue research
